version: '3'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: greinvinicios/nginx
        container_name: nginx
        ports:
            - "80:80"
        networks: 
            - minha-network
        depends_on: 
            - "node1"
            - "node2"
            - "node3"

    mongodb:
        image: mongo
        networks: 
            - minha-network

    node1:
        build:
            dockerfile: ./docker/books.dockerfile
            context: .
        image: greinvinicios/books
        container_name: books-1
        ports:
            - "3000"
        networks: 
            - minha-network
        depends_on:
            - "mongodb"

    node2:
        build:
            dockerfile: ./docker/books.dockerfile
            context: .
        image: greinvinicios/books
        container_name: books-2
        ports:
            - "3000"
        networks: 
            - minha-network
        depends_on:
            - "mongodb"

    node3:
        build:
            dockerfile: ./docker/books.dockerfile
            context: .
        image: greinvinicios/books
        container_name: books-3
        ports:
            - "3000"
        networks: 
            - minha-network
        depends_on:
            - "mongodb"

networks: 
    minha-network:
        driver: bridge
